name: IntoChest
version: 1.6 Beta
main: atpx.minecraft.IntoChest
author: atpx, Joghurt
description: >
  This plugin pushes items that lie on a Workbench automatically into a Chest 
  or Dispenser.
  The Chest/Dispenser can be seated directly besides the Workbench or be 
  connected to it via Redstone Wire of infinite length.
  Multiple Chests/Dispensers can be linked with Redstone Wire for in case a 
  Chest/Dispenser is full.
  Filtering is possible using Signs within the Redstone Wire line labeled with
  the english name of the Block/Item
    (see http://www.minecraftwiki.net/wiki/Data_values ) or its decimal ID to 
    let that type 'pass' that Sign.
  You can also use common parts of Block/Item names to group them, like 
  "stairs" will fit for wooden, brick or stone stairs.
  Filtering multiple Blocks/Items is also possible by simply separating 
  their names/IDs by comma.
  A single "*" on a sign means "use this path only in case nothing else 
  matches". This is not necessary all the time but
  a fix for if you encounter Blocks/Items in a non-filtered Chest/Dispenser 
  while there is a special filtered one for them.
commands:
   intochest:
      description: IntoChest commands.
      usage: IntoChest invalid usage. Type "/<command> help" for valid options.
      aliases: ic
